"""
Gradio frontend for process sequence prediction.

Run:  python app.py
Then: open http://localhost:7860
"""

import csv
import io
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "models"))

import gradio as gr

from models.infer import (
    available_models,
    load_model,
    missing_models,
    run_task1,
    run_task2,
    run_task3,
    self_benchmark_task1,
    self_benchmark_task2,
    _levenshtein,
    _major_block,
    _block_sig,
    _safe_div,
)
from models.lcm.validator import validate_sequence

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT = Path(__file__).parent
_EVAL_VALID = _ROOT / "data" / "participant_files" / "eval_input_valid.csv"
_EVAL_ANOMALY = _ROOT / "data" / "participant_files" / "eval_input_anomaly.csv"

_EXTENDED_CSVS = [
    _ROOT / "data" / "raw" / "MOSFET" / "MOSFET_extended.csv",
    _ROOT / "data" / "raw" / "IGBT" / "IGBT_extended.csv",
    _ROOT / "data" / "raw" / "IC" / "IC_extended.csv",
]

_VARIANT_CSVS = [
    _ROOT / "data" / "raw" / "MOSFET" / "MOSFET_variants.csv",
    _ROOT / "data" / "raw" / "IGBT" / "IGBT_variants.csv",
    _ROOT / "data" / "raw" / "IC" / "IC_variants.csv",
]

# ---------------------------------------------------------------------------
# Model cache
# ---------------------------------------------------------------------------

_model_cache: dict = {}


def _get_model(name: str):
    if name not in _model_cache:
        _model_cache[name] = load_model(name)
    return _model_cache[name]


# ---------------------------------------------------------------------------
# Input parsing
# ---------------------------------------------------------------------------


def _parse_input(text: str) -> list[str]:
    lines = text.strip().splitlines()
    if not lines:
        return []
    if "," in lines[0] and any(k in lines[0].upper() for k in ("SEQUENCE_ID", "STEP")):
        steps = []
        for line in lines[1:]:
            parts = line.split(",", 1)
            if len(parts) >= 2:
                steps.append(parts[1].strip())
        return steps
    if " -> " in text or " → " in text:
        return [s.strip() for s in text.replace("→", "->").split("->") if s.strip()]
    return [line.strip() for line in lines if line.strip()]


def _fmt_violations(violations: list[str]) -> str:
    if not violations:
        return "No rule violations detected"
    lines = [f"{len(violations)} rule(s) violated:"]
    for v in violations:
        lines.append(f"  - {v}")
    return "\n".join(lines)


def _handle_upload(file) -> str:
    if file is None:
        return ""
    with open(file, "r") as f:
        return f.read()


# ---------------------------------------------------------------------------
# Eval dataset loader (30 sequences for eval button)
# ---------------------------------------------------------------------------


def _load_eval_sequences(n_sequences: int = 30, seed: int = 123) -> list[tuple[str, list[str]]]:
    """
    Load n_sequences ground truth sequences from extended CSVs (10 per family).
    Returns list of (family, full_step_list).
    """
    rng = random.Random(seed)
    candidates = _EXTENDED_CSVS if any(p.exists() for p in _EXTENDED_CSVS) else _VARIANT_CSVS
    per_family = max(1, n_sequences // 3)
    result = []

    for path in candidates:
        if not path.exists():
            continue
        family = path.stem.split("_")[0].upper()
        seqs: dict[str, list[str]] = {}
        with path.open(newline="", encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                sid = row.get("SEQUENCE_ID", "").strip()
                step = row.get("STEP", "").strip()
                if sid and step:
                    seqs.setdefault(sid, []).append(step)

        ids = list(seqs.keys())
        rng.shuffle(ids)
        for sid in ids[:per_family]:
            result.append((family, seqs[sid]))

    return result[:n_sequences]


# ---------------------------------------------------------------------------
# Eval metrics (mirrors eval_metrics.py logic)
# ---------------------------------------------------------------------------


def _run_eval_all_tasks(model_name: str) -> str:
    """
    Run evaluation on 30 autogenerated sequences for all 3 tasks.
    Returns formatted metrics string.
    """
    if not model_name:
        return "No model selected."

    model = _get_model(model_name)
    seqs = _load_eval_sequences(n_sequences=30)
    if not seqs:
        return "No data found. Expected *_extended.csv or *_variants.csv in data/raw/."

    lines = [
        "=" * 60,
        f"  EVALUATION — {model_name} — 30 sequences (10 per family)",
        "=" * 60,
        "",
    ]

    # ── Task 1: Next-Step Prediction ──────────────────────────────────────
    top1 = top3 = top5 = total = 0
    rr = 0.0
    for family, steps in seqs:
        n = len(steps)
        # Sample positions between 20% and 80%
        positions = list(range(max(2, n // 5), int(n * 0.8), max(1, n // 10)))
        for pos in positions:
            prefix = steps[:pos]
            true_next = steps[pos]
            preds = model.predict_next(prefix, top_k=5)
            h1 = bool(preds) and preds[0] == true_next
            h3 = true_next in preds[:3]
            h5 = true_next in preds[:5]
            r = 1.0 / (preds.index(true_next) + 1) if true_next in preds else 0.0
            top1 += h1; top3 += h3; top5 += h5; rr += r; total += 1

    lines += [
        "─" * 60,
        "TASK 1 — NEXT-STEP PREDICTION",
        "─" * 60,
        f"  Positions evaluated : {total}",
        f"  Top-1 Accuracy     : {_safe_div(top1, total):.4f}",
        f"  Top-3 Accuracy     : {_safe_div(top3, total):.4f}",
        f"  Top-5 Accuracy     : {_safe_div(top5, total):.4f}",
        f"  MRR                : {_safe_div(rr, total):.4f}",
        "",
    ]

    # ── Task 2: Sequence Completion ───────────────────────────────────────
    ned_all = []; exact_all = []; tacc_all = []; bacc_all = []
    for family, steps in seqs:
        n = len(steps)
        for frac in (0.6, 0.8):
            cut = int(n * frac)
            prefix = steps[:cut]
            ref = steps[cut:]
            if not ref:
                continue
            predicted = model.predict_completion(prefix)
            ned = _levenshtein(predicted, ref) / max(len(predicted), len(ref), 1)
            exact = predicted == ref
            m = min(len(predicted), len(ref))
            tacc = sum(p == r for p, r in zip(predicted, ref)) / m if m else 0.0
            bacc = (sum(p == r for p, r in zip(_block_sig(predicted), _block_sig(ref)))
                    / max(len(_block_sig(ref)), 1))
            ned_all.append(ned); exact_all.append(exact)
            tacc_all.append(tacc); bacc_all.append(bacc)

    def mean(lst):
        return sum(lst) / len(lst) if lst else float("nan")

    lines += [
        "─" * 60,
        "TASK 2 — SEQUENCE COMPLETION",
        "─" * 60,
        f"  Sequences evaluated : {len(ned_all)}",
        f"  Mean NED (↓ better) : {mean(ned_all):.4f}",
        f"  Exact Match Rate    : {mean(exact_all):.4f}  ({sum(exact_all)}/{len(exact_all)})",
        f"  Mean Token Accuracy : {mean(tacc_all):.4f}",
        f"  Mean Block Accuracy : {mean(bacc_all):.4f}",
        "",
    ]

    # ── Task 3: Anomaly Detection ─────────────────────────────────────────
    # Create anomalies by injecting random swaps / deletions into half the seqs
    rng = random.Random(456)
    anomaly_seqs = []
    labels = []

    # Valid sequences (first 15)
    for family, steps in seqs[:15]:
        anomaly_seqs.append(steps)
        labels.append(1)  # valid

    # Invalid sequences (last 15 with injected anomalies)
    for family, steps in seqs[15:30]:
        mutated = list(steps)
        n = len(mutated)
        # Apply 2-3 random mutations
        for _ in range(rng.randint(2, 3)):
            mutation = rng.choice(["swap", "delete", "duplicate"])
            if mutation == "swap" and n > 5:
                i, j = rng.sample(range(2, n - 1), 2)
                mutated[i], mutated[j] = mutated[j], mutated[i]
            elif mutation == "delete" and n > 10:
                idx = rng.randint(2, n - 2)
                mutated.pop(idx)
                n -= 1
            elif mutation == "duplicate" and n > 5:
                idx = rng.randint(2, n - 2)
                mutated.insert(idx, mutated[idx])
                n += 1
        anomaly_seqs.append(mutated)
        labels.append(0)  # invalid

    tp = tn = fp = fn = 0
    pred_scores = []
    for seq, gt_label in zip(anomaly_seqs, labels):
        is_valid, score, rule = model.detect_anomaly(seq)
        pred_label = 1 if is_valid else 0
        pred_scores.append(score)
        if gt_label == 1 and pred_label == 1:
            tn += 1
        elif gt_label == 1 and pred_label == 0:
            fp += 1
        elif gt_label == 0 and pred_label == 0:
            tp += 1
        else:
            fn += 1

    n_total = len(labels)
    accuracy = (tp + tn) / n_total
    prec = _safe_div(tp, tp + fp)
    rec = _safe_div(tp, tp + fn)
    f1 = _safe_div(2 * prec * rec, prec + rec)

    # ROC-AUC
    pos_sc = [s for s, l in zip(pred_scores, labels) if l == 1]
    neg_sc = [s for s, l in zip(pred_scores, labels) if l == 0]
    if pos_sc and neg_sc:
        total_pairs = len(pos_sc) * len(neg_sc)
        conc = sum(p > n for p in pos_sc for n in neg_sc)
        tied = sum(p == n for p in pos_sc for n in neg_sc)
        auc = (conc + 0.5 * tied) / total_pairs
        auc_str = f"{auc:.4f}"
    else:
        auc_str = "n/a"

    lines += [
        "─" * 60,
        "TASK 3 — ANOMALY DETECTION",
        "─" * 60,
        f"  Sequences evaluated : {n_total}  (15 valid + 15 mutated)",
        f"  Binary Accuracy     : {accuracy:.4f}",
        f"  Precision           : {prec:.4f}",
        f"  Recall              : {rec:.4f}",
        f"  F1 Score            : {f1:.4f}",
        f"  ROC-AUC             : {auc_str}",
        f"  Confusion: TP={tp}  FP={fp}  FN={fn}  TN={tn}",
        "",
    ]

    lines += ["=" * 60, "  Evaluation complete.", "=" * 60]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Interactive tab handlers
# ---------------------------------------------------------------------------


def predict_next(input_text: str, model_name: str) -> tuple[str, str]:
    if not input_text.strip():
        return "No input provided.", ""
    if not model_name:
        return "No model selected.", ""
    steps = _parse_input(input_text)
    if not steps:
        return "Could not parse any steps.", ""

    model = _get_model(model_name)
    top5 = model.predict_next(steps, top_k=10)

    lines = [
        f"Model   : {model_name}",
        f"Prefix  : {len(steps)} steps  (last: {steps[-1]})",
        "",
        "Top-10 Next Step Predictions",
        "─" * 52,
    ]
    for rank, step in enumerate(top5, 1):
        lines.append(f"  {rank:2d}.  {step}")

    viols = validate_sequence(steps)
    return "\n".join(lines), _fmt_violations(viols)


def predict_completion(input_text: str, model_name: str) -> tuple[str, str, str]:
    if not input_text.strip():
        return "No input provided.", "", ""
    if not model_name:
        return "No model selected.", "", ""
    steps = _parse_input(input_text)
    if not steps:
        return "Could not parse any steps.", "", ""

    model = _get_model(model_name)
    completion = model.predict_completion(steps)

    lines = [
        f"Model     : {model_name}",
        f"Prefix    : {len(steps)} steps",
        f"Generated : {len(completion)} steps",
        "",
        "Completion",
        "─" * 52,
    ]
    for i, s in enumerate(completion, 1):
        lines.append(f"  {i:3d}.  {s}")
    if not completion:
        lines.append("  (no completion produced)")

    in_viols = _fmt_violations(validate_sequence(steps))
    out_viols = _fmt_violations(validate_sequence(steps + completion))
    return "\n".join(lines), in_viols, out_viols


def detect_anomaly_interactive(input_text: str, model_name: str) -> tuple[str, str]:
    if not input_text.strip():
        return "No input provided.", ""
    if not model_name:
        return "No model selected.", ""
    steps = _parse_input(input_text)
    if not steps:
        return "Could not parse any steps.", ""

    model = _get_model(model_name)
    is_valid, score, rule = model.detect_anomaly(steps)

    verdict = "VALID" if is_valid else "INVALID"
    lines = [
        f"Model   : {model_name}",
        f"Steps   : {len(steps)}",
        f"Verdict : {verdict}",
        f"Score   : {score:.4f}  (higher = more likely valid)",
    ]
    if rule:
        lines.append(f"Rule    : {rule}")

    viols = validate_sequence(steps)
    return "\n".join(lines), _fmt_violations(viols)


# ---------------------------------------------------------------------------
# Benchmark tab handlers
# ---------------------------------------------------------------------------


def _check_eval_files() -> tuple[bool, bool]:
    return _EVAL_VALID.exists(), _EVAL_ANOMALY.exists()


def run_benchmark(model_name: str, task: str) -> tuple[str, str]:
    """Returns (scores_text, download_csv_str)."""
    if not model_name:
        return "No model selected.", ""

    valid_ok, anomaly_ok = _check_eval_files()

    model = _get_model(model_name)
    log_lines = []

    def progress(done, total):
        log_lines.append(f"  {done}/{total} sequences processed...")

    if task == "Task 1 — Next-Step Prediction":
        if not valid_ok:
            return f"Eval file not found:\n  {_EVAL_VALID}", ""
        pred_csv, scores = run_task1(model, _EVAL_VALID, progress_cb=progress)
        return scores + "\n\n" + "\n".join(log_lines), pred_csv

    elif task == "Task 2 — Sequence Completion":
        if not valid_ok:
            return f"Eval file not found:\n  {_EVAL_VALID}", ""
        pred_csv, scores = run_task2(model, _EVAL_VALID, progress_cb=progress)
        return scores + "\n\n" + "\n".join(log_lines), pred_csv

    elif task == "Task 3 — Anomaly Detection":
        if not anomaly_ok:
            return f"Eval file not found:\n  {_EVAL_ANOMALY}", ""
        pred_csv, scores = run_task3(model, _EVAL_ANOMALY, progress_cb=progress)
        return scores + "\n\n" + "\n".join(log_lines), pred_csv

    return "Unknown task.", ""


def run_self_benchmark(model_name: str, task: str, n_seqs: int) -> tuple[str, str]:
    if not model_name:
        return "No model selected.", ""
    model = _get_model(model_name)
    log = []

    def progress(done, total):
        log.append(f"  {done}/{total} sequences processed...")

    if "Task 1" in task:
        scores, pred_csv = self_benchmark_task1(
            model, progress_cb=progress, max_per_family=n_seqs
        )
    elif "Task 2" in task:
        scores, pred_csv = self_benchmark_task2(
            model, progress_cb=progress, max_per_family=n_seqs
        )
    else:
        return (
            "Self-benchmark not available for Task 3 (uses rule-checker by definition).",
            "",
        )

    return scores + "\n\n" + "\n".join(log), pred_csv


def save_predictions(pred_csv: str, task: str) -> str:
    """Write pred_csv to a temp file and return the path for gr.File download."""
    if not pred_csv.strip():
        return None
    slug = task.split("—")[0].strip().lower().replace(" ", "_")
    out_path = _ROOT / f"predictions_{slug}.csv"
    out_path.write_text(pred_csv)
    return str(out_path)


# ---------------------------------------------------------------------------
# Build Gradio app
# ---------------------------------------------------------------------------


def build_app():
    models = available_models()
    default = models[0] if models else None

    if not models:
        print(
            "[WARNING] No trained model checkpoints found. "
            "Train models first or place checkpoints in the expected paths."
        )

    valid_ok, anomaly_ok = _check_eval_files()
    eval_status = []
    if valid_ok:
        eval_status.append(f"eval_input_valid.csv found ({_EVAL_VALID})")
    else:
        eval_status.append(
            f"eval_input_valid.csv NOT FOUND (expected at {_EVAL_VALID})"
        )
    if anomaly_ok:
        eval_status.append(f"eval_input_anomaly.csv found ({_EVAL_ANOMALY})")
    else:
        eval_status.append(
            f"eval_input_anomaly.csv NOT FOUND (expected at {_EVAL_ANOMALY})"
        )

    with gr.Blocks(title="Process Sequence Predictor") as app:
        gr.Markdown("# Semiconductor Process Sequence Predictor")
        missing = missing_models()
        missing_note = ""
        if missing:
            missing_note = "\n\n**Not yet trained:** " + "  |  ".join(
                f"`{n}` (expected `{p}`)" for n, p in missing.items()
            )
        gr.Markdown(
            "**Models available:** "
            + (
                ", ".join(f"`{m}`" for m in models)
                if models
                else "_none — train first_"
            )
            + missing_note
            + "\n\n**Eval files:** "
            + " | ".join(eval_status)
        )

        # ── Tab 1: Evaluate (Test Dataset) ───────────────────────────────────
        with gr.Tab("Evaluate"):
            gr.Markdown(
                "### Full Evaluation on 30 Ground-Truth Sequences\n\n"
                "Runs **all 3 tasks** on 30 sequences sampled from `*_extended.csv` "
                "(10 per family: MOSFET, IGBT, IC).\n\n"
                "- **Task 1 — Next-Step:** Top-1/3/5 Accuracy, MRR\n"
                "- **Task 2 — Completion:** NED, Exact Match, Token Accuracy, Block Accuracy\n"
                "- **Task 3 — Anomaly:** Accuracy, Precision, Recall, F1, ROC-AUC\n\n"
                "For anomaly detection, 15 sequences are kept valid and 15 are mutated "
                "(random swaps/deletions/duplications) to create ground-truth anomalies."
            )
            with gr.Row():
                eval_model_dd = gr.Dropdown(
                    choices=models,
                    value=default,
                    label="Model",
                    scale=2,
                )
                eval_btn = gr.Button(
                    "Run Evaluation", variant="primary", scale=1
                )
            eval_output = gr.Textbox(
                label="Evaluation Results",
                lines=35,
                max_lines=50,
                interactive=False,
            )
            eval_btn.click(
                fn=_run_eval_all_tasks,
                inputs=[eval_model_dd],
                outputs=[eval_output],
            )

        # ── Tab 2: Self-Benchmark ────────────────────────────────────────────
        with gr.Tab("Self-Benchmark"):
            gr.Markdown(
                "Scores against `*_extended.csv` sequences — independent from "
                "`*_variants.csv` training data, so no leakage for variant-trained models. "
                "Falls back to variants if extended not found.\n\n"
                "**Task 1:** samples every ~5th position between 10%–90% of each sequence, "
                "predicts top-5 next steps, checks if the true next step appears at rank 1, 3, or 5. "
                "MRR = mean 1/rank of the correct answer.\n\n"
                "**Task 2:** cuts each sequence at 60% and 80%, runs greedy completion to EOS, "
                "compares predicted vs ground-truth suffix. "
                "NED = Levenshtein / max(|pred|,|ref|) (lower is better). "
                "Block Accuracy maps steps to 10 coarse phases before comparing.\n\n"
                "Sequences per family controls sample size — lower is faster."
            )
            with gr.Row():
                self_task_dd = gr.Dropdown(
                    choices=[
                        "Task 1 — Next-Step Prediction",
                        "Task 2 — Sequence Completion",
                    ],
                    value="Task 1 — Next-Step Prediction",
                    label="Task",
                    scale=2,
                )
                self_model_dd = gr.Dropdown(
                    choices=models,
                    value=default,
                    label="Model",
                    scale=1,
                )
            with gr.Row():
                n_seqs_slider = gr.Slider(
                    minimum=5,
                    maximum=100,
                    value=50,
                    step=5,
                    label="Sequences per family  (Task 1: 50 · Task 2: 15 recommended)",
                    scale=3,
                )
                self_run_btn = gr.Button("Run", variant="primary", scale=1)
            self_scores_box = gr.Textbox(
                label="Results",
                lines=20,
                max_lines=40,
                interactive=False,
            )
            with gr.Row():
                self_pred_state = gr.State("")
                self_dl_btn = gr.Button("Download Predictions CSV", scale=1)
                self_dl_file = gr.File(label="Predictions", scale=3)
            self_run_btn.click(
                fn=run_self_benchmark,
                inputs=[self_model_dd, self_task_dd, n_seqs_slider],
                outputs=[self_scores_box, self_pred_state],
            )
            self_dl_btn.click(
                fn=save_predictions,
                inputs=[self_pred_state, self_task_dd],
                outputs=[self_dl_file],
            )

        # ── Tab 3: Official ──────────────────────────────────────────────────
        with gr.Tab("Official"):
            gr.Markdown(
                "Generates submission CSVs from the organiser-provided eval files. "
                "Ground-truth labels are not included — download the CSV and submit to the organizers.\n\n"
                "| Task | Input | Model does | Metrics (scored by organizers) |\n"
                "|---|---|---|---|\n"
                "| **1 — Next-Step** | `eval_input_valid.csv` (600 partial seqs) | Predict top-5 next steps | Top-1/3/5 Accuracy, MRR |\n"
                "| **2 — Completion** | `eval_input_valid.csv` | Greedy decode to EOS | NED, Exact Match, Token Acc, Block Acc |\n"
                "| **3 — Anomaly** | `eval_input_anomaly.csv` (987 seqs) | Classify valid/invalid + confidence score | Binary Acc, F1, ROC-AUC, Rule Attribution |\n"
            )
            with gr.Row():
                task_dd = gr.Dropdown(
                    choices=[
                        "Task 1 — Next-Step Prediction",
                        "Task 2 — Sequence Completion",
                        "Task 3 — Anomaly Detection",
                    ],
                    value="Task 1 — Next-Step Prediction",
                    label="Task",
                    scale=2,
                )
                bench_model_dd = gr.Dropdown(
                    choices=models,
                    value=default,
                    label="Model",
                    scale=1,
                )
                run_btn = gr.Button("Run", variant="primary", scale=1)
            scores_box = gr.Textbox(
                label="Results",
                lines=20,
                max_lines=40,
                interactive=False,
            )
            with gr.Row():
                pred_state = gr.State("")
                dl_btn = gr.Button("Download Predictions CSV", scale=1)
                dl_file = gr.File(label="Predictions", scale=3)
            run_btn.click(
                fn=run_benchmark,
                inputs=[bench_model_dd, task_dd],
                outputs=[scores_box, pred_state],
            )
            dl_btn.click(
                fn=save_predictions,
                inputs=[pred_state, task_dd],
                outputs=[dl_file],
            )

        # ── Tab 4: Custom (interactive predict) ──────────────────────────────
        with gr.Tab("Custom"):
            with gr.Row(equal_height=True):
                with gr.Column(scale=4):
                    input_box = gr.Textbox(
                        label="Input Sequence",
                        placeholder=(
                            "One step per line, or arrow-separated:\n"
                            "RECEIVE WAFER LOT\nLOT IDENTIFICATION\n...\n\n"
                            "Or paste CSV (SEQUENCE_ID,STEP)"
                        ),
                        lines=18,
                        max_lines=40,
                    )
                    file_up = gr.File(
                        label="Upload CSV", file_types=[".csv", ".txt"], type="filepath"
                    )
                    input_viols = gr.Textbox(
                        label="Input Validation", lines=3, interactive=False
                    )

                with gr.Column(scale=1, min_width=180):
                    gr.Markdown("### Actions")
                    custom_model_dd = gr.Dropdown(
                        choices=models,
                        value=default,
                        label="Model",
                    )
                    btn_next = gr.Button(
                        "Predict Next Step", variant="primary", size="lg"
                    )
                    btn_end = gr.Button(
                        "Predict Until End", variant="primary", size="lg"
                    )
                    btn_anom = gr.Button(
                        "Detect Anomaly", variant="secondary", size="lg"
                    )

                with gr.Column(scale=4):
                    output_box = gr.Textbox(
                        label="Output", lines=18, max_lines=40, interactive=False
                    )
                    output_viols = gr.Textbox(
                        label="Output Validation", lines=3, interactive=False
                    )

            file_up.change(fn=_handle_upload, inputs=[file_up], outputs=[input_box])
            btn_next.click(
                fn=predict_next,
                inputs=[input_box, custom_model_dd],
                outputs=[output_box, input_viols],
            )
            btn_end.click(
                fn=predict_completion,
                inputs=[input_box, custom_model_dd],
                outputs=[output_box, input_viols, output_viols],
            )
            btn_anom.click(
                fn=detect_anomaly_interactive,
                inputs=[input_box, custom_model_dd],
                outputs=[output_box, input_viols],
            )

    return app


if __name__ == "__main__":
    app = build_app()
    app.launch(server_name="127.0.0.1", server_port=7860)
